#!/bin/bash
# @usage ./rsync.sh bitinvo@172.20.100.166:~

echo 'Synchronizing code to '$1
rsync -avz ../bitinvo $1      \
--exclude                     \
'.tmp'                        \
--exclude                     \
'.git'                        \
--exclude                     \
'bitinvo/dist'                \
--exclude                     \
'config/cabinet.js'   \
--exclude                     \
'bower_components'            \
--exclude                     \
"autoprefixer"                \
--exclude                     \
"barrels"                     \
--exclude                     \
"bootstrap-webpack"           \
--exclude                     \
"bower-webpack-plugin"        \
--exclude                     \
"css-loader"                  \
--exclude                     \
"cssnano"                     \
--exclude                     \
"decamelize"                  \
--exclude                     \
"defined"                     \
--exclude                     \
"expose-loader"               \
--exclude                     \
"extract-text-webpack-plugin" \
--exclude                     \
"file-loader"                 \
--exclude                     \
"forever"                     \
--exclude                     \
"grunt-contrib-clean"         \
--exclude                     \
"grunt-contrib-coffee"        \
--exclude                     \
"grunt-contrib-concat"        \
--exclude                     \
"grunt-contrib-copy"          \
--exclude                     \
"grunt-contrib-cssmin"        \
--exclude                     \
"grunt-contrib-jst"           \
--exclude                     \
"grunt-contrib-less"          \
--exclude                     \
"grunt-contrib-uglify"        \
--exclude                     \
"grunt-contrib-watch"         \
--exclude                     \
"grunt-sails-linker"          \
--exclude                     \
"grunt-sync"                  \
--exclude                     \
"grunt-webpack"               \
--exclude                     \
"html-loader"                 \
--exclude                     \
"i18n-webpack-plugin"         \
--exclude                     \
"indexes-of"                  \
--exclude                     \
"jade-loader"                 \
--exclude                     \
"json-loader"                 \
--exclude                     \
"less"                        \
--exclude                     \
"less-loader"                 \
--exclude                     \
"node-libs-browser"           \
--exclude                     \
"object-assign"               \
--exclude                     \
"path-to-regexp"              \
--exclude                     \
"postcss"                     \
--exclude                     \
"postcss-calc"                \
--exclude                     \
"postcss-colormin"            \
--exclude                     \
"postcss-convert-values"      \
--exclude                     \
"postcss-discard-comments"    \
--exclude                     \
"postcss-discard-duplicates"  \
--exclude                     \
"postcss-discard-empty"       \
--exclude                     \
"postcss-discard-unused"      \
--exclude                     \
"postcss-filter-plugins"      \
--exclude                     \
"postcss-loader"              \
--exclude                     \
"postcss-merge-idents"        \
--exclude                     \
"postcss-merge-longhand"      \
--exclude                     \
"postcss-merge-rules"         \
--exclude                     \
"postcss-minify-font-values"  \
--exclude                     \
"postcss-minify-gradients"    \
--exclude                     \
"postcss-minify-params"       \
--exclude                     \
"postcss-minify-selectors"    \
--exclude                     \
"postcss-normalize-charset"   \
--exclude                     \
"postcss-normalize-url"       \
--exclude                     \
"postcss-ordered-values"      \
--exclude                     \
"postcss-reduce-idents"       \
--exclude                     \
"postcss-reduce-transforms"   \
--exclude                     \
"postcss-svgo"                \
--exclude                     \
"postcss-unique-selectors"    \
--exclude                     \
"postcss-value-parser"        \
--exclude                     \
"postcss-zindex"              \
--exclude                     \
"sails-hook-autoreload"       \
--exclude                     \
"sails-memory"                \
--exclude                     \
"style-loader"                \
--exclude                     \
"url-loader"                  \
--exclude                     \
"webpack"                     \
--exclude                     \
"webpack-dev-server"          